apiVersion: v1
data:
  main: |
   package dataapi.authz

   rule[{"name": "Only allow administrator access to unsafe assets", "action": "BlockResource"}]{
       input.situationStatus == "unsafe-high"
       input.request.role != "Admin"
   }

kind: ConfigMap
metadata:
   creationTimestamp: null
   labels:
     openpolicyagent.org/policy: rego
   name: example-policy
   namespace: default

